openapi: 3.0.0
info:
  title: BIN Lookup API
  description: >-
    BIN lookup API, the free api service from bintable.com to lookup card
    information using it's BIN. the service maintains updated database based on
    the comunity and other third party services to make sure all BINs in the
    database are accurate and up to date.
  contact:
    email: hello@bintable.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0-oas3
servers:
  - url: 'https://api.bintable.com/v1'
tags:
  - name: Lookup
    description: Authorized users with API Key can call this service
  - name: Balance
    description: Authorized users with API Key can call endpoints under this tag.
paths:
  '/{bin}':
    get:
      tags:
        - Lookup
      summary: Lookup for bin
      description: |
        By passing in the appropriate BIN, you can lookup for
        card meta data in bintable.com API
      operationId: binLookup
      parameters:
        - name: bin
          in: path
          description: pass the required BIN code
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: api_key
          in: query
          description: 'The API key, which you can get from bintable.com website.'
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: BIN data response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseItem'
        '401':
          description: 'Your balance is exhausted,or package expired'
        '403':
          description: Invalid API Key
        '422':
          description: API key is missing
  /balance:
    get:
      tags:
        - Balance
      summary: Check Balance
      description: Get Account balance and expiry
      operationId: balanceLookup
      parameters:
        - name: api_key
          in: query
          description: 'The API key, which you can get from bintable.com website.'
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Balance reponse
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseItem'
        '401':
          description: 'Your balance is exhausted,or package expired'
        '403':
          description: Invalid API Key
        '422':
          description: API key is missing
components:
  schemas:
    ResponseItem:
      required:
        - data
        - message
        - result
      type: object
      properties:
        result:
          type: integer
          example: 200
        message:
          type: string
          example: SUCCESS
        data:
          type: object
          properties:
            card:
              type: object
              properties:
                scheme:
                  type: string
                type:
                  type: string
                category:
                  type: string
                length:
                  type: integer
                checkluhn:
                  type: integer
                cvvlen:
                  type: integer
            country:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
                flag:
                  type: string
                currency:
                  type: string
                currency_code:
                  type: string
            bank:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                phone:
                  type: string
